### ISSUE TITLE
Can't find Twitch player

### ISSUE THREAD

**Issue by djangoliv** [data-exp-lab/jupyterlab_twitch#13]
I installed the extension but I can't find the player in the command panel (or anywhere else).

```
jupyter labextension install @data-exp-lab/jupyterlab-twitch
pip install jupyterlab-twitch  # not sure this one is necessary
```

I also tried the code 

```
import jupyterlab_twitch
player = jupyterlab_twitch.TwitchPlayerModel()
player.channel = "mst3k"
player.volume = 0.9
display(player)
```

in a notebook (after installing ipywidgets) but without success.
=> Error displaying widget: model not found

The extension manager display that @data-exp-lab/jupyterlab-twitch is enabled.
There is no error in terminal.

Regards,

**Comment by matthewturk** [comment]
Hi -- are you running this in jupyterlab specifically?  Or in jupyter
notebook?

**Comment by djangoliv** [comment]
It works now. Thanks

**Comment by matthewturk** [comment]
Oh, thank you for updating me!  I am sorry I did not get back to you.  I
lost track of time when the semester began.

**Comment by andeplane** [comment]
What was the solution? I'm having the same issue right now :)

**Comment by andeplane** [comment]
I have tried using a Dockerfile like this
```
FROM jupyter/datascience-notebook

RUN pip install widgetsnbextension
RUN pip install ipywidgets
RUN pip install ipympl
RUN jupyter nbextension enable --py widgetsnbextension

RUN pip install jupyterlab_iframe
RUN jupyter labextension install jupyterlab_iframe
RUN jupyter serverextension enable --py jupyterlab_iframe

RUN pip install jupyterlab-twitch
RUN jupyter labextension install @data-exp-lab/jupyterlab-twitch
```

**Comment by djangoliv** [comment]
sorry that no longer works on my side either.

**Comment by matthewturk** [comment]
So I'm really not sure why it isn't working.  One thought I had was that there is maybe an issue with the installation of the javascript side of it.

Are either or both of you running jupyterlab 3.0?  I am going to spend a little time when I can trying to get this to work with the pre-built bundles, which should simplify the installation.  That might fix the issues you're seeing, too.

**Comment by matthewturk** [comment]
@djangoliv @andeplane I've just updated this to use jupyterlab 3, which should simplify the javascript packaging.  Can you give a try with `jupyterlab-twitch` 0.2.0 and see if it's still a problem?

**Comment by djangoliv** [comment]
@matthewturk I tested and it works perfectly. Thanks !
